/*
-- Query: SELECT * FROM minkyoung.product
LIMIT 0, 1000

-- Date: 2022-02-10 17:43
*/
INSERT INTO `` (`prd_id`,`prd_name`,`prd_price`,`prd_photo`,`prd_content`,`prd_group`) VALUES (1,'ESSENTIEL',3300000,'../upload/product/sopa_3.jpeg','우아하면서도 심플한 라인에 퀄팅으로 안정감과 귀여움을 더한 세련된 소파','FURNISHING');
INSERT INTO `` (`prd_id`,`prd_name`,`prd_price`,`prd_photo`,`prd_content`,`prd_group`) VALUES (2,'AVANT APRES',2490000,'../upload/product/sopa_1.jpeg','구성과 움직임을 가볍게 분리할 수 있으면서도 견고한 고급 가죽과 호두나무 사이드 테이블의 조화가 우아한 볼수록 더욱 매혹적인 소파','FURNISHING');
INSERT INTO `` (`prd_id`,`prd_name`,`prd_price`,`prd_photo`,`prd_content`,`prd_group`) VALUES (3,'Oatemeal Plate',40000,'../upload/product/plate_01.jpg','곡식과 흙의 질감을 색으로 표현하였으며, 넉넉한 크기로 메인요리 및 브런치 등을 담기에 좋습니다.','COOKING');
INSERT INTO `` (`prd_id`,`prd_name`,`prd_price`,`prd_photo`,`prd_content`,`prd_group`) VALUES (4,'RENDEZ VOUS',4360000,'../upload/product/sopa_2.jpg','누군가와 함께 소파에 앉아 편안한 이야기를 할 수 있는 유연한 디자인의 소파','FURNISHING');
INSERT INTO `` (`prd_id`,`prd_name`,`prd_price`,`prd_photo`,`prd_content`,`prd_group`) VALUES (5,'Oatemeal Cup',25000,'../upload/product/cup_04.jpg','곡식과 흙의 질감을 색으로 표현하였으며, 커피 또는 차를 마시기ㅣ 좋습니다.','COOKING');
INSERT INTO `` (`prd_id`,`prd_name`,`prd_price`,`prd_photo`,`prd_content`,`prd_group`) VALUES (6,'Blackdot Cup',25000,'../upload/product/cup_05.png','검은반무광에 흰색점이 흩뿌려져있는 숏머그입니다. 커피 또는 차를 마시기 좋습니다.','COOKING');
INSERT INTO `` (`prd_id`,`prd_name`,`prd_price`,`prd_photo`,`prd_content`,`prd_group`) VALUES (7,'BlackdotLong Cup',25000,'../upload/product/cup_06.png','검은반무광에 흰색점이 흩뿌려져있는 숏머그입니다. 넉넉한 용량으로 실용적입니다.','COOKING');
INSERT INTO `` (`prd_id`,`prd_name`,`prd_price`,`prd_photo`,`prd_content`,`prd_group`) VALUES (8,'Spring Teacup',21800,'../upload/product/cup_07.png','차를 따를 시 벚꽃 형태의 그라데이션이 보이는 아름다운 찻잔입니다. 이중기벽으로 제작되어 냉온음료의 온도를 오랫동안 유지시켜 줍니다.','COOKING');
INSERT INTO `` (`prd_id`,`prd_name`,`prd_price`,`prd_photo`,`prd_content`,`prd_group`) VALUES (9,'Moon Bottle/Cup',51000,'../upload/product/cup_08.png','밤하늘빛 오묘한 색의 유약과 금빛 달이 들어가 더욱 특별한 술자리를 만들어줍니다.','COOKING');
INSERT INTO `` (`prd_id`,`prd_name`,`prd_price`,`prd_photo`,`prd_content`,`prd_group`) VALUES (10,'NEW YORK SUITE',3800000,'../upload/product/sopa_7.jpg','사바 이탈리아는 멋진 선과 포근함이 공존하는 아름다움에 사람이 앉았을 때 그 사람을 더 아름답게 비춰줍니다.','FURNISHING');
INSERT INTO `` (`prd_id`,`prd_name`,`prd_price`,`prd_photo`,`prd_content`,`prd_group`) VALUES (11,'EDISON THE PETIT RESIDENCE ENVY GREEN',138000,'../upload/product/light_1.jpg','Fatboy의 Edison the Petit Residence는 스타일리쉬한 멀티유즈 선반 입니다. 쁘띠 레지던스는 2개의 피스로 벽에 고정시켜 거는 방식으로 벽선반으로 사용 할 수도, 선반이나 수납장 위에 올려 사용 할 수도 있습니다. ','LIGHTING');
INSERT INTO `` (`prd_id`,`prd_name`,`prd_price`,`prd_photo`,`prd_content`,`prd_group`) VALUES (12,'EDISON THE PETIT RESIDENCE PINE GREEN',138000,'../upload/product/light_2.jpg','Fatboy의 Edison the Petit Residence는 스타일리쉬한 멀티유즈 선반 입니다. 쁘띠 레지던스는 2개의 피스로 벽에 고정시켜 거는 방식으로 벽선반으로 사용 할 수도, 선반이나 수납장 위에 올려 사용 할 수도 있습니다. ','LIGHTING');
INSERT INTO `` (`prd_id`,`prd_name`,`prd_price`,`prd_photo`,`prd_content`,`prd_group`) VALUES (13,'ADD THE WALLY WHITE',208000,'../upload/product/light_3.gif','Add The Wally는 레트로 스타일의 무선 터치 벽 램프입니다. 벽면에 못만 있으면 걸어 둘 수 있는 벽 등으로 램프를 가볍게 터치하면 ON/OFF 와 3단계의 밝기 조절이 가능합니다. 침실 벽 등, 복도 등, 출입구 조명 등 다양하게 사용 가능하며 실내외에서 사용할 수 있습니다. ','LIGHTING');
INSERT INTO `` (`prd_id`,`prd_name`,`prd_price`,`prd_photo`,`prd_content`,`prd_group`) VALUES (14,'ADD THE WALLY TAUPE',208000,'../upload/product/light_4.jpg','Add The Wally는 레트로 스타일의 무선 터치 벽 램프입니다. 벽면에 못만 있으면 걸어 둘 수 있는 벽 등으로 램프를 가볍게 터치하면 ON/OFF 와 3단계의 밝기 조절이 가능합니다. 침실 벽 등, 복도 등, 출입구 조명 등 다양하게 사용 가능하며 실내외에서 사용할 수 있습니다. ','LIGHTING');
INSERT INTO `` (`prd_id`,`prd_name`,`prd_price`,`prd_photo`,`prd_content`,`prd_group`) VALUES (15,'BOLLEKE LAMP RED',208000,'../upload/product/light_5.jpg','Bolleke는 충전식으로 휴대가 편리한 무선 램프입니다. 점등될 때, 아이코닉한 둥근 모양이 진주를 닮았으며 균일한 빛을 만들어 냅니다. 실내와 실외 모두 사용 가능한 제품으로 나무, 천장 틀, 파라솔 등 원하는 곳에 걸어서 사용할 수 있습니다. ','LIGHTING');
INSERT INTO `` (`prd_id`,`prd_name`,`prd_price`,`prd_photo`,`prd_content`,`prd_group`) VALUES (16,'BOLLEKE LAMP RED',208000,'../upload/product/light_6.gif','Bolleke는 충전식으로 휴대가 편리한 무선 램프입니다. 점등될 때, 아이코닉한 둥근 모양이 진주를 닮았으며 균일한 빛을 만들어 냅니다. 실내와 실외 모두 사용 가능한 제품으로 나무, 천장 틀, 파라솔 등 원하는 곳에 걸어서 사용할 수 있습니다. ','LIGHTING');
INSERT INTO `` (`prd_id`,`prd_name`,`prd_price`,`prd_photo`,`prd_content`,`prd_group`) VALUES (17,'TRANSLOETJE TRANSPARENT',220000,'../upload/product/light_7.jpg','할머니의 빈티지램프에서 영감을 받은 Transloetje 테이블 램프 클리어입니다. 폴리카보네이트 소재로 램프 내부의 클래식한 전구가 그대로 노출되어 고전적인 매력이 돋보이는 제품입니다. USB 충전, 콘센트 충전으로 최대 8시간까지 지속되며, 충전중에도 사용 가능합니다','LIGHTING');
INSERT INTO `` (`prd_id`,`prd_name`,`prd_price`,`prd_photo`,`prd_content`,`prd_group`) VALUES (18,'TRANSLOETJE BROWN',220000,'../upload/product/light_8.jpg','할머니의 빈티지램프에서 영감을 받은 Transloetje 테이블 램프 클리어입니다. 폴리카보네이트 소재로 램프 내부의 클래식한 전구가 그대로 노출되어 고전적인 매력이 돋보이는 제품입니다. USB 충전, 콘센트 충전으로 최대 8시간까지 지속되며, 충전중에도 사용 가능합니다','LIGHTING');
INSERT INTO `` (`prd_id`,`prd_name`,`prd_price`,`prd_photo`,`prd_content`,`prd_group`) VALUES (19,'TRANSLOETJE BLUE',220000,'../upload/product/light_9.jpg','할머니의 빈티지램프에서 영감을 받은 Transloetje 테이블 램프 클리어입니다. 폴리카보네이트 소재로 램프 내부의 클래식한 전구가 그대로 노출되어 고전적인 매력이 돋보이는 제품입니다. USB 충전, 콘센트 충전으로 최대 8시간까지 지속되며, 충전중에도 사용 가능합니다','LIGHTING');
INSERT INTO `` (`prd_id`,`prd_name`,`prd_price`,`prd_photo`,`prd_content`,`prd_group`) VALUES (20,'TRANS-PARENTS DARK GREY',720000,'../upload/product/light_10.gif','할머니의 빈티지램프에서 영감을 받은 Transloetje의 아쉬웠던 사이즈를 충족시키는 중형 버전인 Trans-parents입니다. 테이블 위에서도 너무 크지 않고, 받침이 작아 차지하는 면적이 넓지 않습니다. 폴리카보네이트 소재로 램프 내부의 클래식한 전구가 그대로 노출되어 고전적인 매력이 돋보이는 제품입니다. 집 또는 사무실에서 야간조명, 발코니의 분위기있는 조명, 책상 조명 등으로 사용할 수 있는 조명입니다.','LIGHTING');
INSERT INTO `` (`prd_id`,`prd_name`,`prd_price`,`prd_photo`,`prd_content`,`prd_group`) VALUES (21,'FIR GREEN & BRASS 12” GLOBE LIGHT',258000,'../upload/product/light_11.jpg','Fir Green & Brass 12\" Globe Light는 사무실, 라운지 또는 복도에서 장식적인 오브제로 사용하기에 좋은 전나무색 그린 컬러의 황동 스탠드 지구본입니다. 밤에 침실등, 서재등, 거실등으로 사용할 수 있으며, USB 케이블을 연결하는 타입으로 케이블에 전원 ON/OFF 버튼이 있습니다.','LIGHTING');
INSERT INTO `` (`prd_id`,`prd_name`,`prd_price`,`prd_photo`,`prd_content`,`prd_group`) VALUES (22,'CITY LIGHTS 12\" GLOBE LIGHT',258000,'../upload/product/light_12.jpg','City Light 12\" Globe Light는 사무실, 라운지 또는 복도에서 장식적인 오브제로 사용하기에 좋은 시티 라이트 지구본입니다. 인구밀도가 높은 도시는 더 선명하게, 광활한 대지의 나라에서는 불빛이 없는 곳도 있어 실제로 우주에서 지구를 내려다보는 것 같은 느낌을 줍니다. 밤에 침실등, 서재등, 거실등으로 사용할 수 있으며, USB 케이블을 연결하는 타입으로 케이블에 전원 ON/OFF 버튼이 있습니다.','LIGHTING');
INSERT INTO `` (`prd_id`,`prd_name`,`prd_price`,`prd_photo`,`prd_content`,`prd_group`) VALUES (23,'PALAIS SOFA',5290000,'../upload/product/sopa_9.jpg','다양한 모듈의 색상과 소재들로 구성할 수 있는 지능적이고 명확하게 설계뙨 시스템의 완성체. 위트만 콜렉션의 새로운 앙상블.','FURNISHING');
INSERT INTO `` (`prd_id`,`prd_name`,`prd_price`,`prd_photo`,`prd_content`,`prd_group`) VALUES (24,'GEO',1800000,'../upload/product/sopa_4.jpg','귀여운 라인과 앉았을 때의 안락함. 그리고 고급스러운 메탈릭의 디테일. 보기만 해도 기분 좋아지는 사랑스러운 체어','FURNISHING');
INSERT INTO `` (`prd_id`,`prd_name`,`prd_price`,`prd_photo`,`prd_content`,`prd_group`) VALUES (25,'MY TAOS',4060000,'../upload/product/sopa_5.jpg','기억, 편안함, 디자인 그리고 우아함을 기반으로 소파의 정석을 부드러운 라인으로 완성한 소파','FURNISHING');
INSERT INTO `` (`prd_id`,`prd_name`,`prd_price`,`prd_photo`,`prd_content`,`prd_group`) VALUES (26,'LAX BENCH',4260000,'../upload/product/sopa_6.jpeg','고급진 소재의 시트와 렉스 콜렉션의 심플하고 멋진 라인을 가진 아름다운 디자인','FURNISHING');
INSERT INTO `` (`prd_id`,`prd_name`,`prd_price`,`prd_photo`,`prd_content`,`prd_group`) VALUES (27,'MOUNT BANCH',3960000,'../upload/product/sopa_8.jpg','시원하게 그려지는 곡선과 시트의 풍성한 깊이감. 그리고 최고급 친환경 천연가죽이 주는 만족감','FURNISHING');
INSERT INTO `` (`prd_id`,`prd_name`,`prd_price`,`prd_photo`,`prd_content`,`prd_group`) VALUES (28,'VARAN TABLE',3240000,'../upload/product/table_1.jpg','비대칭의 조화가 안정적인 디자인이 되는 고대의 아름다움 같기도 하며 미래의 모던함인 것 같기도 한 디자인','FURNISHING');
INSERT INTO `` (`prd_id`,`prd_name`,`prd_price`,`prd_photo`,`prd_content`,`prd_group`) VALUES (29,'P68 TABLE',3370000,'../upload/product/table_2.jpg','보는 위치에 따라 달라보이는 유니크함. 새롭게도 두개 상판으로 다리의 두께감을 만들어낸 P68만의 미학적인 멋짐.','FURNISHING');
INSERT INTO `` (`prd_id`,`prd_name`,`prd_price`,`prd_photo`,`prd_content`,`prd_group`) VALUES (30,'Blooming Plate_Circle',40000,'../upload/product/plate_02.jpg','그릇에 볼록한 곡선들이 채워져 풍성한 꽃 잎과 식물의 라인을 이룹니다. 브런치,디저트등을 올리기 좋은 사이즈의 타원형접시이며 앞뒤 양면으로 사용이 가능해 더욱 실용적입니다. 또한 반무광의 백색유약에 갈색과 검은 점이 자연스럽게 피어있습니다.','COOKING');
INSERT INTO `` (`prd_id`,`prd_name`,`prd_price`,`prd_photo`,`prd_content`,`prd_group`) VALUES (31,'STONEWARE TEA POT BLACK',108000,'../upload/product/cup_09.jpg','삶을 조금 더 조화롭고 아름답게 만들어 집집마다 ERNST만의 향을 전합니다. 또한, 모던하고 심플한 홈 스타일링을 제안하여 아늑하고 따스한 나만의 공간을 한결 더 편안한 공간으로 만들어 줍니다. 모던하면서도 클래식한 디자인의 스톤웨어 티팟입니다. 외부는 무광택으로 마감 처리되어있고, 내부와 뚜껑은 유약 처리되어 멋진 대비를 만들어냄으로서 어디에 두어도 멋진 모습을 연출합니다. ERNST 티팟은 같은 시리즈의 찻잔 및 커피잔과 잘 어울립니다.','COOKING');
INSERT INTO `` (`prd_id`,`prd_name`,`prd_price`,`prd_photo`,`prd_content`,`prd_group`) VALUES (32,'STONEWARE BOWL BLACK',38000,'../upload/product/cup_10.jpg','삶을 조금 더 조화롭고 아름답게 만들어 집집마다 ERNST만의 향을 전합니다. 또한, 모던하고 심플한 홈 스타일링을 제안하여 아늑하고 따스한 나만의 공간을 한결 더 편안한 공간으로 만들어 줍니다. 모던하면서도 클래식한 디자인의 스톤웨어 볼입니다. 외부는 무광택으로 마감 처리되어있고 내부와 뚜껑은 유약 처리되어 멋진 대비를 만들어냄으로서 어디에 두어도 멋진 모습을 연출합니다. ERNST 볼은 같은 시리즈의 찻잔, 티팟 그리고 커피잔과 잘 어울립니다.','COOKING');
INSERT INTO `` (`prd_id`,`prd_name`,`prd_price`,`prd_photo`,`prd_content`,`prd_group`) VALUES (33,'STONEWARE BOWL TEA CUP BLACK',34000,'../upload/product/cup_11.jpg','삶을 조금 더 조화롭고 아름답게 만들어 집집마다 ERNST만의 향을 전합니다. 또한, 모던하고 심플한 홈 스타일링을 제안하여 아늑하고 따스한 나만의 공간을 한결 더 편안한 공간으로 만들어 줍니다. 모던하면서도 클래식한 디자인의 스톤웨어 볼입니다. 외부는 무광택으로 마감 처리되어있고 내부와 뚜껑은 유약 처리되어 멋진 대비를 만들어냄으로서 어디에 두어도 멋진 모습을 연출합니다. ERNST 볼은 같은 시리즈의 찻잔, 티팟 그리고 커피잔과 잘 어울립니다.','COOKING');
